import {Link, useParams} from 'react-router';
import type {ApiGenerationResponse} from '../../../src/libs/admin/api_types';
import {generationPath, taskPath, useApi} from '../api';
import {Empty, KvTable, Layout, Loading, TaskHeading, Warning} from '../ui/Layout';
import {GenerationsTable} from '../ui/GenerationsTable';
import {Result} from '../ui/Result';

export default function GenerationPage() {
    const params = useParams()
    const taskId = params.taskId!
    const generationId = params.generationId!
    const {data, error} = useApi<ApiGenerationResponse>(generationPath(taskId, generationId))
    const title = `Generation ${generationId}`

    if (error || !data) {
        return <Layout title={title}>
            {error ? <><Warning>{error}</Warning><p><Link to={taskPath(taskId)}>← Back to task</Link></p></> : <Loading/>}
        </Layout>
    }

    const row = data.generation

    return <Layout title={title}>
        <TaskHeading heading={data.heading}/>
        <p><Link to={taskPath(taskId)}>← Back to task</Link></p>
        {data.mismatch ? <Warning>{data.mismatch}</Warning> : null}

        <h2>Generation</h2>
        <KvTable rows={[
            ['Task directory', data.heading.task_dir],
            ['Generation id', row.generation_id],
            ['Type', row.generation_type],
            ['Model', row.model],
            ['First generated by (user / platform)', `${row.user_id || '—'} / ${row.platform_label}`],
            ['Created at', row.created_at || '—'],
            ['Expires at', row.expires_at ? `${row.expires_at} (${row.expired ? 'expired' : 'valid'})` : 'never'],
        ]}/>

        <h2>Prompt</h2>
        {row.prompt ? <pre>{row.prompt}</pre> : <Empty>Not recorded (generation cached before the prompt column existed).</Empty>}

        <h2>Result</h2>
        <Result result={row.generation_result}/>

        <h2>All generations by this user on this task</h2>
        {data.same_set
            ? <GenerationsTable rows={data.same_set} currentGenerationId={row.generation_id}/>
            : <Empty>User or platform not recorded for this generation.</Empty>}
    </Layout>
}
